#!/bin/sh

###########################################################################
#
#    Copyright (c) 2011/2012 Signey John
#    
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#    
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#    
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#    
###########################################################################


# 4 aceita mountLabel - montando tudo em /mnt/
# faz e2fsck de particoes ext? ...

#######################################
erro() {
 xxl="$debugr"
 debugr=y
 log "$1" 5
 debugr="$xxl"
}
#######################################
log() {
 echo "$1"
 if [ $2 ] && [ $debugs ]; then
  sleep $2
 elif [ $2 ] && [ $debugr ]; then
  echo "enter..."
  read xent
  while [ ".$xent" != "." ]; do
	$xent
	read xent
  done
 fi
}
#######################################
mkDir() {
 if ! test -e $1 ; then
  mkdir $1
 fi
}
#######################################
#cheka part recebe label...
Fsck() {
 if [ ".$(blkid | grep ${1} | grep 'TYPE=\"ext')" != "." ]; then
  log "e2fsck /dev/disk/by-label/${1} .... " 2
  /sbin/e2fsck -p -v "/dev/disk/by-label/${1}"
 fi
}
#######################################
montar() {
	lb=$1
	md=mount
	if [ ".$(blkid | grep ${lb} | grep ntfs)" != "." ]; then
	 modprobe -v ntfs
	 for xx in /sbin/mount.ntfs-3g /sbin/ntfs-3g; do
	  if test -x "$xx"; then
	    log "ntfs $xx .... " 2
		md="$xx"
		break
	  fi
	 done
	fi
	Fsck $lb
	$md "/dev/disk/by-label/${lb}" $2
	if [ $? -ne 0 ]; then
		erro "ERRO $md /dev/disk/by-label/${lb} $2"
	fi
}
#######################################
bb=/bin/busybox
if test -e $bb ; then
	$bb --install -s
fi


[ -d /dev ] || mkdir -m 0755 /dev
[ -d /root ] || mkdir -m 0700 /root
[ -d /sys ] || mkdir /sys
[ -d /proc ] || mkdir /proc
[ -d /tmp ] || mkdir /tmp
mkdir -p /var/lock
mount -t sysfs -o nodev,noexec,nosuid none /sys 
mount -t proc -o nodev,noexec,nosuid none /proc 

grep -q '\<quiet\>' /proc/cmdline || echo "Loading, please wait..."

# Note that this only becomes /dev on the real filesystem if udev's scripts
# are used; which they will be, but it's worth pointing out
if ! mount -t devtmpfs -o mode=0755 none /dev; then
	mount -t tmpfs -o mode=0755 none /dev
	mknod -m 0600 /dev/console c 5 1
	mknod /dev/null c 1 3
fi
mkdir /dev/pts
mount -t devpts -o noexec,nosuid,gid=5,mode=0620 none /dev/pts || true
> /dev/.initramfs-tools
mkdir /dev/.initramfs

##########################################
echo "# Parse command line options"
opV="chr debug debugr debugs debugl debugx rootLabel rootPath root runLevel init mountLabel"
runLevel=2
init=/sbin/init
for x in $(cat /proc/cmdline); do
	oo=0
	for i in $opV BOOT_IMAGE; do
		if [ $(echo "===${x}"|grep "===${i}=") ]; then
			echo "  $x"
			eval $x
			oo=1
		elif [ ".$x" == ".$i" ] ; then
			eval "$x=y"
			oo=1
		fi
	done
	if [ $oo -eq 0 ]; then
		log "  **opcao boot invalida $x
  **opcoes validas: $opV
  **ENTER para continuar...
  *************************" 5
		#read
	fi
	if [ "$x" == "debugl" ]; then
		debugL=/initrd.log
		debug=y
		quiet=n
		exec >$debugL 2>&1
		set -x
	fi
	if [ "$x" == "debugx" ]; then
		set -x
	fi
done
log "rootLabel=$rootLabel" 
log "rootPath=$rootPath" 3


for i in 1 2 3 4 5 6; do
	[ -c /dev/tty$i ] || mknod /dev/tty$i c 4 $i
done
#/scripts/init-top/console_setup

# It's all over netlink now
echo "" > /proc/sys/kernel/hotplug
	
# Start the udev daemon to process events
/sbin/udevd --daemon --resolve-names=never

# Iterate sysfs and fire off everything; if we include a rule for it then
# it'll get handled; otherwise it'll get handled later when we do this again
# in the main boot sequence.
( /sbin/udevadm trigger --subsystem-match=block; \
  /sbin/udevadm trigger --subsystem-nomatch=block; ) &


#if [ -f /root/dev/.initramfs/plymouth.pid ]
#then
#	/bin/plymouth update-root-fs --new-root-dir=/root
#fi

################################################  
################################################  

modprobe -v ext3
modprobe -v ext4
modprobe -v aufs
modprobe -v loop #debian precisa
modprobe -v squashfs
log "probes" 3

echo "################################"
echo "espera por LABEL $rootLabel"
x="."
while ! test -e "/dev/disk/by-label/${rootLabel}"; do
	echo $x
	x=".$x"
	sleep 1
	#ls /dev/disk/by-label
done
echo "################################"

mkDir /mnt
drr=/mnt/initrd
mkDir $drr
mkDir $drr/sis


montar $rootLabel $drr/sis


ls $drr/sis
log "foi...$drr/sis" 3
rdist="$drr/sis/${rootPath}"
if ! test -d $rdist ; then
 erro "ERRO dir distrib $rdist nao encontrado!" 
fi

#montar outros
if ! test -z $mountLabel ; then
	mountLabel=$(echo $mountLabel|tr ';' ' '|tr ',' ' ')
	for i in $mountLabel; do
		if ! test -e $drr/$i; then mkdir $drr/$i;fi
		montar $i $drr/$i
	done
fi

##monta o file system root
if [ ".$root" == "." ]; then
 root=$(cat $rdist/fstab)
else
 root=$(echo $root|tr ';' ' '|tr ',' ' ')
fi

##################################
# monta roots para aufs
nm=0
opAufs=""
for i in $root; do
 #comeca com /?
 if [ $(echo "===${i}"|grep "===/") ]; then
	x=0
 else
	i=$rdist/$i
 fi
 log "$nm $i" 5
 
 if test -d $i; then
  d=$i
 else
  d=$drr/r_$nm
  nm="${nm}0"
  #$(echo $nm+1|busybox bc)
  mkDir $d
  if test -b $i; then
	mount $i $d
	if [ $? -ne 0 ]; then
	  erro "ERRO mount $i $d"
	fi	
  elif test -f $i; then
	mount -o loop $i $d
	if [ $? -ne 0 ]; then
	  erro "ERRO mount -o loop $i $d"
	fi	
  else
	erro "ERRO não existe $i" 
  fi
 fi
 # primeiro sempre rw, o resto ro
 if [ ".$opAufs" == "." ]; then
  opAufs="$d=rw"
 else
  opAufs="$opAufs:$d=rr"
 fi	
done
log "ROOTaufs=$opAufs" 
mount -t aufs -o noatime,dirs=$opAufs aufs /root
ls /root
log "foi...aufs /root" 30

#move tudo para novo ROOT
# ao shutdown loop nao pode desmontar raiz porque
# raiz depende de mounts q estao dentro dela...
mkDir /root/mnt
mkDir /root/mnt/initrd
for i in $drr/*; do
 x=$(basename $i)
 mkDir /root/mnt/initrd/$x
 mount -n -o move $i /root/mnt/initrd/$x
done

#debugl
if [ $debugL ]; then
 mkDir /root/var
 mkDir /root/var/log
 mv $debugL /root/var/log
fi

log "##############################
moveu monts..." 3


#se nao matar o X fica sem mouse, teclado...
pkill udevd
killall udevd


# Move virtual filesystems over to the real filesystem
mount -n -o move /dev /root/dev
#mount -n -o bind /dev /root/dev
mount -n -o move /sys /root/sys
mount -n -o move /proc /root/proc
log "foi...mount -n -o move rootmnt=/root
@=$@" 3

#br-abnt2
#chroot /root /usr/sbin/install-keymap us
#echo "foi...teclado"
#sleep 3

#parte inutil, fixar em run-init... ou setado..
if [ ".$chr" == "." ]; then
 for d in bin sbin; do
  for i in run-init switch_root; do
   ch=/$d/$i
   if test -x $ch ; then
    chr=$ch
    break
   fi
  done
  if [ ".$chr" != "." ]; then
   break
  fi
 done
fi


log "chroot para $chr" 10
exec $chr /root $init $runLevel  </root/dev/console >/root/dev/console 2>&1
echo "Could not execute run-init."
exit


#exec switch_root /root /sbin/init 2
#exec run-init /root ${init} "$@" </root/dev/console >/root/dev/console 2>&1
#ls /root/bash
#exec /bin/busybox chroot /root /sbin/init 2



